from fastapi import FastAPI

from .apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="API Avito shop",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
