services:
  avito-shop-service:
    container_name: avito-shop-service
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:4000"
    environment:
      - DB_URL=postgresql://postgres:password@db:5432/shop
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  db:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

networks:
  internal:
